_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/retinanet_r50_fpn.yml',
  '_base_/optimizer_1x.yml',
  '_base_/retinanet_reader.yml',
]

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ShuffleNetV2_x1_0_pretrained.pdparams

RetinaNet:
  backbone: ShuffleNetV2

ShuffleNetV2:
  scale: 1.0
  feature_maps: [5, 13, 17]
  act: leaky_relu

TestReader:
  inputs_def:
    image_shape: [3, 800, 800]
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [800, 800], keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: false